### ISSUE TITLE
Doesn't seem to work?

### ISSUE THREAD

**Issue by HarrisDraiic** [Sideways-Sky/RealisticSleep#1]
Hello! I'm new to submitting issues to GitHub. Forgive me if this could be done better _(advice welcome lol)_.

Installed your plugin, attempted to sleep, was notified I was asleep and then the % of the night passed appeared but it was not moving. I have an exception that was thrown in console for you, posted below.

I am on Paper 1.21.1.

```
[00:53:45 WARN]: [RealisticSleep] Task #1480 for RealisticSleep v1.1 generated an exception
java.lang.ArithmeticException: / by zero
        at RealisticSleep-1.1.jar/net.sideways_sky.realisticsleep.SleepingWorld.update(SleepingWorld.java:31) ~[RealisticSleep-1.1.jar:?]
        at RealisticSleep-1.1.jar/net.sideways_sky.realisticsleep.Events.lambda$update$1(Events.java:27) ~[RealisticSleep-1.1.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[paper-1.21.1.jar:1.21.1-89-1ed64f8]
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:475) ~[paper-1.21.1.jar:1.21.1-89-1ed64f8]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1724) ~[paper-1.21.1.jar:1.21.1-89-1ed64f8]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:473) ~[paper-1.21.1.jar:1.21.1-89-1ed64f8]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1596) ~[paper-1.21.1.jar:1.21.1-89-1ed64f8]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1302) ~[paper-1.21.1.jar:1.21.1-89-1ed64f8]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.1.jar:1.21.1-89-1ed64f8]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

Let me know if there's anything else you need to know!

**Comment by pigeon-paddy** [comment]
Hey, the same just happened to me - use command 
"gamerule playersSleepingPercentage 100"
to reset it back to default - this plugin probably tries to calculate the required players for sleeping and devides by zero, if you´re alone on the server.
Cheers Patrick

**Comment by robtherobz** [comment]
> Hey, the same just happened to me - use command "gamerule playersSleepingPercentage 100" to reset it back to default - this plugin probably tries to calculate the required players for sleeping and devides by zero, if you´re alone on the server. Cheers Patrick

Doesn't seem to work for me unfortunately :(

[15:45:09 WARN]: [RealisticSleep] Task #2691 for RealisticSleep v1.2 generated an exception
java.lang.NullPointerException: Cannot invoke "net.sideways_sky.realisticsleep.SleepingWorld.update()" because "world" is null
	at RealisticSleep-1.2.jar//net.sideways_sky.realisticsleep.Events.lambda$update$1(Events.java:27) ~[?:?]
	at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:78) ~[paper-1.21.11.jar:1.21.11-131-6d5b910]
	at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:474) ~[paper-1.21.11.jar:1.21.11-131-6d5b910]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1756) ~[paper-1.21.11.jar:1.21.11-131-6d5b910]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1611) ~[paper-1.21.11.jar:1.21.11-131-6d5b910]
	at net.minecraft.server.dedicated.DedicatedServer.tickServer(DedicatedServer.java:427) ~[paper-1.21.11.jar:1.21.11-131-6d5b910]
	at net.minecraft.server.MinecraftServer.processPacketsAndTick(MinecraftServer.java:1667) ~[paper-1.21.11.jar:1.21.11-131-6d5b910]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1335) ~[paper-1.21.11.jar:1.21.11-131-6d5b910]
	at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:388) ~[paper-1.21.11.jar:1.21.11-131-6d5b910]

For me, the plugin works fine as long as I don't change or touch the config, If I do, it refuses to work until I completely uninstall it from the server and reinstall it.
